include: "rules/common.smk"
include: "rules/normalise.smk"
include: "rules/annotate.smk"
include: "rules/ped.smk"
include: "rules/panel_filtering.smk"
include: "rules/scout_load_config.smk"
include: "rules/misc.smk"

rule all:
    input: outfiles, load_configs
