include: "rules/common.smk"
include: "rules/normalise.smk"
include: "rules/trios.smk"
include: "rules/annotate.smk"
include: "rules/ped.smk"
include: "rules/peddy.smk"
include: "rules/panel_filtering.smk"
include: "rules/filtering.smk"
include: "rules/scout_load_config.smk"
include: "rules/misc.smk"


ruleorder: copy_results > tabix
ruleorder: copy_results > bgzip


rule all:
    input:
        outfiles,
        load_configs,
