samples: "samples.tsv"
resources: "resources.yaml"

genome_build: "37"
scout_owner: "clingen"

default_container: ""

reference:
  fasta: /storage/userdata/references/homo_sapiens/hg19/fasta/hg19.fa.gz

decompose:
  container: docker://hydragenetics/vt:2015.11.10

bgzip:
  container: docker://hydragenetics/common:0.1.1

tabix:
  container: docker://hydragenetics/common:0.1.1

vcfanno:
  container: docker://clinicalgenomics/vcfanno:0.3.2
  base_path: "/storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37"
  config_uri: "https://raw.githubusercontent.com/gmc-norr/config-files/main/{track}/vcfanno/grch37_vcfanno_config_{version}.toml"
  config_version:
    rare_disease: "0.1"
    cancer: "0.1"

vep:
  container: docker://hydragenetics/vep:105
  cache: /storage/userdata/references/homo_sapiens/vep/vep_data_105
  cache_type: merged
  plugin: /storage/userdata/references/homo_sapiens/vep/vep_data_105/plugins
  plugin-data: /storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37
  swegen: /storage/userdata/references/homo_sapiens/hg19/index/swegen_20180409/anon-SweGen_STR_NSPHS_1000samples_SNV_hg19.vcf.gz
  clinvar: /storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37/clinvar_20220730/clinvar_20220730.vcf.gz
  mode: --offline --cache

genmod:
  container: docker://quay.io/biocontainers/genmod:3.7.4--pyh5e36f6f_0
  rank_model_uri: "https://raw.githubusercontent.com/gmc-norr/config-files/main/{track}/rank_model/{track}_rank_model_{version}.ini"
  rank_model_version:
    rare_disease: "0.1"
    cancer: "0.1"
