samples: "samples.tsv"

output_directory: results

default_container: docker://snakemake/snakemake:v9.14.0

reference:
  fasta: /storage/userdata/references/homo_sapiens/hg19/fasta/hg19.fa.gz

vcfanno:
  base_path: "/storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37"
  config: "/storage/userdata/config-files/scout-annotation/cancer/vcfanno/grch37_vcfanno_config_0.1.toml"

vep:
  cache: /storage/userdata/references/homo_sapiens/vep/vep_data_105
  cache_type: merged
  plugin: /storage/userdata/references/homo_sapiens/vep/vep_data_105/plugins
  plugin-data: /storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37
  swegen: /storage/userdata/references/homo_sapiens/hg19/index/swegen_20180409/anon-SweGen_STR_NSPHS_1000samples_SNV_hg19.vcf.gz
  clinvar: /storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37/clinvar_20220730/clinvar_20220730.vcf.gz
  mode: --offline --cache

genmod:
  rank_model: "/storage/userdata/config-files/scout-annotation/cancer/rank_model/cancer_rank_model_0.1.ini"


