samples: "samples.tsv"

genome_build: "37"
scout_owner: "clingen"
output_directory: results

default_container: docker://snakemake/snakemake:v9.14.0

vcf_filter:
  rare_disease: rare_disease_filter.yaml
  somatic: somatic_filter.yaml

reference:
  fasta: /storage/userdata/references/homo_sapiens/hg19/fasta/hg19.fa.gz

vcfanno:
  base_path: "/storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37"

vcfanno_config:
  extra: --insecure

vep:
  cache: /storage/userdata/references/homo_sapiens/vep/vep_data_105
  cache_type: merged
  plugin: /storage/userdata/references/homo_sapiens/vep/vep_data_105/plugins
  plugin-data: /storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37
  swegen: /storage/userdata/references/homo_sapiens/hg19/index/swegen_20180409/anon-SweGen_STR_NSPHS_1000samples_SNV_hg19.vcf.gz
  clinvar: /storage/userdata/references/homo_sapiens/vep/vep_plugin_data/GRCh37/clinvar_20220730/clinvar_20220730.vcf.gz
  mode: --offline --cache

#genmod:
#  rank_model: ""

genmod_rank_model:
  extra: --insecure

