filters:
  - name: common variation
    description: >
      Exclude variants that have a frequency of >= 1%  within gnomAD or SweGen.
    expression: >
      (CSQ["gnomAD_AF"] is NA or CSQ["gnomAD_AF"] < 0.01)
      and
      (CSQ["SweGen_AF"] is NA or float(CSQ["SweGen_AF"]) < 0.01)

  - name: intronic variants
    description: >
      Exclude intronic variants that are not annotated as splice variants or
      have been previously reported in COSMIC.
    expression: >
        re.search("intron_variant", CSQ["Consequence"])
        or
        re.search("splice", CSQ["Consequence"])
        or
        any(re.search("COSV\d+", x) for x in CSQ["Existing_variation"])

  - name: allele depth
    description:
      Only include variants have >= 5 supporting reads for the alternative
      allele.
    expression: >
      FORMAT["AO"][0] >= 5

  - name: vaf
    description: >
      Only include variants with a VAF >= 1%
    expression: >
      FORMAT["AF"][0] >= 0.01

