name: Linting

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: |
          pip install --upgrade pip

      - name: Install dev dependencies
        run: |
          pip install --group dev

      - name: Run snakefmt check
        run: |
          snakefmt --diff --check workflow/

      - name: Run black check
        run: |
          black --target-version py312 --diff --check workflow/
